package mail

import (
	"io"
	"strings"

	"github.com/fatih/color"
)

// ColorPalette gives colors to names.
type ColorPalette map[string]*color.Color

var (
	// cp is the ColorPalette I use to render messages generated by this
	// library.
	cp = ColorPalette{
		"base":   color.New(color.FgHiBlack),
		"meh":    color.New(color.FgHiBlack),
		"fail":   color.New(color.FgHiRed),
		"warn":   color.New(color.FgHiYellow),
		"pass":   color.New(color.FgHiGreen),
		"header": color.New(color.FgMagenta),
		"action": color.New(color.FgWhite),
		"label":  color.New(color.FgBlue),
		"value":  color.New(color.FgCyan),
		"file":   color.New(color.FgWhite),

		"reading":    color.New(color.FgHiMagenta),
		"labeling":   color.New(color.FgHiGreen),
		"forwarding": color.New(color.FgHiYellow),
		"moving":     color.New(color.FgHiCyan),
		"clearing":   color.New(color.FgHiBlue),
		"dropping":   color.New(color.FgHiYellow),
		"searching":  color.New(color.FgHiMagenta),
		"fixing":     color.New(color.FgHiCyan),
	}
)

// Join returns a string that is the same as would be created by calling
//
//	strings.Join(args, d)
//
// but with the separator colored using the given color.
func (cp ColorPalette) Join(cname string, args []string, d string) string {
	if c, ok := cp[cname]; ok {
		return strings.Join(args, c.Sprint(d))
	} else {
		panic("unknown color " + cname)
	}
}

// Fcolor takes an alternating set of string arguments. The even number strings
// name colors and the odd number strings are strings that will be written to
// out in the previously named color.
func (cp ColorPalette) Fcolor(out io.Writer, args ...string) {
	cname := "base"
	for i, v := range args {
		if i%2 == 0 {
			cname = v
		} else {
			if c, ok := cp[cname]; ok {
				c.Fprint(out, v)
			} else {
				panic("unknown color " + cname)
			}
		}
	}
}

// Scolor takes an alternating set of string arguments. The even number strings
// name colors and the odd number strings are strings that will be colored by
// the previously named color. The strings will be concatenated and returned.
func (cp ColorPalette) Scolor(args ...string) string {
	var out strings.Builder
	cname := "base"
	for i, v := range args {
		if i%2 == 0 {
			cname = v
		} else {
			if c, ok := cp[cname]; ok {
				c.Fprint(&out, v)
			} else {
				panic("unknown color " + cname)
			}
		}
	}
	return out.String()
}

// Fprintf formats the string using the fmt and args, colors it with the color,
// and writes it out to the given io.Writer.
func (cp ColorPalette) Fprintf(cname string, out io.Writer, fmt string, args ...interface{}) {
	if c, ok := cp[cname]; ok {
		c.Fprintf(out, fmt, args...)
		return
	}
	panic("unknown cname " + cname)
}

// Sprintf formats the string using the fmt and args, colors it with the color,
// and returns it as a string.
func (cp ColorPalette) Sprintf(cname string, fmt string, args ...interface{}) string {
	if c, ok := cp[cname]; ok {
		return c.Sprintf(fmt, args...)
	}
	panic("unknown color " + cname)
}
